[package]
name = "kujira-rs-testing"
version = "1.7.3"
authors = ["Kujira Labs"]
edition = "2018"
description = "Interfaces and utilities for Kujira cosmwasm contracts"
license = "Apache-2.0"
homepage = "https://kujira.app"
repository = "https://github.com/Team-Kujira/kujira-rs"

[features]

[dependencies]
cosmwasm-std = { workspace = true, default-features = false, features = [
    "cosmwasm_1_3",
] }
cosmwasm-schema = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true, default-features = false, features = ["derive"] }
cw-multi-test = { workspace = true, default-features = false, features = [
    "staking",
    "stargate",
    "cosmwasm_1_4",
] }
cw-storage-plus = { workspace = true }
anyhow = { workspace = true }
kujira = { path = "../kujira", version = "1.3" }
serde_json = { workspace = true }
base64 = "0.22"
hex = { workspace = true }
cw20 = { workspace = true }
sha2 = "0.10.8"
bech32 = "0.11"
