[package]
name = "kujira-bow"
version.workspace = true
edition = "2021"
authors = ["Kujira Labs"]
description = "Interfaces for Kujira's BOW"
license = "Apache-2.0"
repository = "https://github.com/Team-Kujira/kujira-rs/tree/master/packages/kujira-bow"

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true, default-features = false }
thiserror = "1"
kujira-std = { path = "../kujira-std", version = "1.1.0" }
kujira-fin = { path = "../kujira-fin", version = "1.1.0" }
