[package]
name = "kujira-std"
version.workspace = true
edition = "2021"
authors = ["Kujira Labs"]
description = "Standard Library and Utilities for Smart Contracts on Kujira"
license = "Apache-2.0"
repository = "https://github.com/Team-Kujira/kujira-rs/tree/master/packages/kujira-std"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = { workspace = true, default-features = false }
cosmwasm-schema = { workspace = true }
cw-storage-plus = { workspace = true }
hex = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
cw20 = { workspace = true }
serde-json-wasm = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
